# Generated by Django 3.0.7 on 2021-03-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='document',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
